apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: proctorx-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3005
    name: backend
  type: LoadBalancer